// Copyright Epic Games, Inc. All Rights Reserved.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using EpicGames.Core;
using EpicGames.UHT.Tables;
using EpicGames.UHT.Types;
using EpicGames.UHT.Utils;

namespace OtterAngleScriptUbtPlugin
{
    /// <summary>
    /// UHT exporter that generates AngelScript binding registration code (.inl) for
    /// all BlueprintCallable / BlueprintPure UFunctions and BlueprintVisible UProperties
    /// found in Engine and Game runtime modules.
    ///
    /// Output: <PluginIntermediate>/GeneratedAngelScriptBindings.inl
    /// Include this file from OtterAngleScript.cpp and call Bind_Generated(Engine).
    /// </summary>
    [UnrealHeaderTool]
    class OtterAngleScriptGeneratorEntry
    {
        [UhtExporter(
            Name = "OtterAngleScript",
            Description = "AngelScript Binding Generator for OtterAngleScript",
            Options = UhtExporterOptions.Default,
            ModuleName = "OtterAngleScript")]
        private static void GenerateAngelScriptBindings(IUhtExportFactory factory)
        {
            new OtterAngleScriptGenerator(factory).Generate();
        }
    }

    class OtterAngleScriptGenerator
    {
        private readonly IUhtExportFactory _factory;

        /// <summary>
        /// Types already manually registered in the C++ plugin.  These are skipped to
        /// avoid double-registration errors.
        /// </summary>
        private static readonly HashSet<string> ManuallyBoundTypes = new(StringComparer.Ordinal)
        {
            "UObject", "UClass",
            "FString", "FName", "FText",
            "FVector", "FVector2D", "FRotator", "FQuat",
            "FTransform", "FPlane", "FBox",
            "FHitResult", "FTimerHandle", "FLatentActionInfo",
            "FActorInstanceHandle",
        };

        public OtterAngleScriptGenerator(IUhtExportFactory factory)
        {
            _factory = factory;
        }

        // -------------------------------------------------------------------------
        // Entry point
        // -------------------------------------------------------------------------

        public void Generate()
        {
#if TRUE
            var packages = _factory.Session.Modules
                .Where(m => m.Module.ModuleType == UHTModuleType.EngineRuntime
                         || m.Module.ModuleType == UHTModuleType.GameRuntime)
                .Select(m => m.ScriptPackage);
#else
            var packages = _factory.Session.Packages
                .Where(p => p.Module.ModuleType == UHTModuleType.EngineRuntime
                         || p.Module.ModuleType == UHTModuleType.GameRuntime);
#endif

            // Collect all UClasses excluding manually-bound types and interfaces.
            var allClasses = packages
                .SelectMany(p => TraverseTree(p))
                .OfType<UhtClass>()
                .Where(c => !c.ClassFlags.HasAnyFlags(EClassFlags.Interface))
                .Where(c => !ManuallyBoundTypes.Contains(c.SourceName))
                .OrderBy(c => c.SourceName)
                .ToList();

            if (allClasses.Count == 0)
                return;

            // Build the set of all type names that will be registered (used to validate
            // struct parameter types later).
            var registeredTypeNames = new HashSet<string>(ManuallyBoundTypes, StringComparer.Ordinal);
            foreach (var cls in allClasses)
                registeredTypeNames.Add(cls.SourceName);

            // Classes that have at least one script-exposed method or property.
            var classesWithContent = allClasses
                .Where(c => HasScriptExposedContent(c))
                .ToList();

            var sb = new StringBuilder();
            WriteFileHeader(sb);
            WriteTypeRegistrations(sb, allClasses);
            WriteMethodWrappers(sb, classesWithContent, registeredTypeNames);
            WriteMethodRegistrations(sb, classesWithContent, registeredTypeNames);
            WriteMasterFunction(sb, classesWithContent);

            string outputPath = _factory.MakePath("GeneratedAngelScriptBindings", ".inl");
            _factory.Session.LogInfo("GeneratedAngelScriptBindings executed! {0}", outputPath);

            _factory.CommitOutput(outputPath, sb);
        }

        // -------------------------------------------------------------------------
        // Sections
        // -------------------------------------------------------------------------

        private static void WriteFileHeader(StringBuilder sb)
        {
            sb.AppendLine("#pragma once");
            sb.AppendLine("// Auto-generated by OtterAngleScript UHT Plugin.");
            sb.AppendLine("// DO NOT EDIT MANUALLY – regenerated on every build.");
            sb.AppendLine("//");
            sb.AppendLine("// Include this file from OtterAngleScript.cpp and call Bind_Generated(Engine)");
            sb.AppendLine("// after all manual bindings have been registered.");
            sb.AppendLine();
        }

        /// <summary>
        /// Emits one RegisterObjectType call per class (forward-declares the type so
        /// parameter/return-type references to any class work regardless of order).
        /// </summary>
        private static void WriteTypeRegistrations(StringBuilder sb, List<UhtClass> allClasses)
        {
            sb.AppendLine("static void OAS_RegisterGeneratedTypes(asIScriptEngine* Engine)");
            sb.AppendLine("{");
            sb.AppendLine("    int Result = 0;");
            foreach (var cls in allClasses)
            {
                sb.AppendLine($"    if (Engine->GetTypeInfoByName(\"{cls.SourceName}\") == nullptr)");
                sb.AppendLine("    {");
                sb.AppendLine($"        Result = Engine->RegisterObjectType(\"{cls.SourceName}\", 0, asOBJ_REF | asOBJ_NOCOUNT | asOBJ_IMPLICIT_HANDLE);");
                sb.AppendLine("        check(Result >= 0);");
                sb.AppendLine("    }");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Emits a namespace of static C++ wrapper functions per class.
        /// Only functions with fully-mappable signatures are included.
        /// </summary>
        private void WriteMethodWrappers(
            StringBuilder sb,
            List<UhtClass> classes,
            HashSet<string> registeredTypeNames)
        {
            foreach (var cls in classes)
            {
                var lines = new List<string>();
                foreach (var func in ScriptFunctions(cls))
                {
                    if (TryBuildWrapper(cls, func, registeredTypeNames, out string? line))
                        lines.Add(line!);
                }

                if (lines.Count == 0) continue;

                sb.AppendLine($"namespace OAS_Gen_{cls.SourceName}");
                sb.AppendLine("{");
                foreach (var line in lines)
                    sb.AppendLine($"    {line}");
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        /// <summary>
        /// Emits per-class registration functions: RegisterObjectMethod + RegisterObjectProperty.
        /// </summary>
        private void WriteMethodRegistrations(
            StringBuilder sb,
            List<UhtClass> classes,
            HashSet<string> registeredTypeNames)
        {
            foreach (var cls in classes)
            {
                sb.AppendLine($"static void OAS_RegisterMethods_{cls.SourceName}(asIScriptEngine* Engine)");
                sb.AppendLine("{");
                sb.AppendLine("    int Result = 0;");
                bool anyContent = false;

                // Methods
                foreach (var func in ScriptFunctions(cls))
                {
                    if (!TryBuildAsSignature(func, registeredTypeNames, out string? asSig))
                        continue;

                    bool isStatic = func.FunctionFlags.HasAnyFlags(EFunctionFlags.Static);
                    string callConv = isStatic ? "asCALL_CDECL" : "asCALL_CDECL_OBJFIRST";

                    sb.AppendLine($"    Result = Engine->RegisterObjectMethod(\"{cls.SourceName}\", \"{asSig}\",");
                    sb.AppendLine($"        asFUNCTION(OAS_Gen_{cls.SourceName}::{func.SourceName}), {callConv});");
                    sb.AppendLine("    check(Result >= 0);");
                    anyContent = true;
                }

                // Properties
                foreach (var prop in ScriptProperties(cls))
                {
                    string? asType = MapPropertyAsType(prop, registeredTypeNames);
                    if (asType == null) continue;

                    sb.AppendLine($"    Result = Engine->RegisterObjectProperty(\"{cls.SourceName}\", \"{asType} {prop.SourceName}\",");
                    sb.AppendLine($"        asOFFSET({cls.SourceName}, {prop.SourceName}));");
                    sb.AppendLine("    check(Result >= 0);");
                    anyContent = true;
                }

                if (!anyContent)
                    sb.AppendLine("    (void)Engine; // nothing to register");

                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        /// <summary>
        /// Emits the master Bind_Generated() function that wires everything together.
        /// </summary>
        private static void WriteMasterFunction(StringBuilder sb, List<UhtClass> classesWithContent)
        {
            sb.AppendLine("// Call Bind_Generated() from StartupModule() to register all auto-generated bindings.");
            sb.AppendLine("// It must be called AFTER all manual bindings (Bind_FString, Bind_UObject, etc.).");
            sb.AppendLine("static void Bind_Generated(asIScriptEngine* Engine)");
            sb.AppendLine("{");
            sb.AppendLine("    check(Engine != nullptr);");
            sb.AppendLine("    OAS_RegisterGeneratedTypes(Engine);");
            foreach (var cls in classesWithContent)
                sb.AppendLine($"    OAS_RegisterMethods_{cls.SourceName}(Engine);");
            sb.AppendLine("}");
        }

        // -------------------------------------------------------------------------
        // Helpers – type traversal & filtering
        // -------------------------------------------------------------------------

        private static IEnumerable<UhtType> TraverseTree(UhtType parent)
        {
            yield return parent;
            if (parent.Children != null)
                foreach (var child in parent.Children.SelectMany(TraverseTree))
                    yield return child;
        }

        private static bool HasScriptExposedContent(UhtClass cls)
        {
            return ScriptFunctions(cls).Any() || ScriptProperties(cls).Any();
        }

        private static IEnumerable<UhtFunction> ScriptFunctions(UhtClass cls)
        {
            return cls.Functions.Where(f =>
                f.FunctionFlags.HasAnyFlags(EFunctionFlags.BlueprintCallable | EFunctionFlags.BlueprintPure));
        }

        private static IEnumerable<UhtProperty> ScriptProperties(UhtClass cls)
        {
            return cls.Children
                .OfType<UhtProperty>()
                .Where(p => !p.PropertyFlags.HasAnyFlags(EPropertyFlags.Parm)
                         && p.PropertyFlags.HasAnyFlags(EPropertyFlags.BlueprintVisible | EPropertyFlags.BlueprintReadOnly));
        }

        // -------------------------------------------------------------------------
        // Helpers – code generation
        // -------------------------------------------------------------------------

        /// <summary>
        /// Tries to build a C++ static wrapper function line for the given UFunction.
        /// Returns false if any parameter/return type cannot be mapped.
        /// </summary>
        private bool TryBuildWrapper(
            UhtClass cls,
            UhtFunction func,
            HashSet<string> registeredTypeNames,
            out string? wrapperLine)
        {
            wrapperLine = null;

            // Return type
            var returnProp = GetReturnProperty(func);
            string cppRet = returnProp != null
                ? MapPropertyCppType(returnProp, isParam: false, registeredTypeNames) ?? ""
                : "void";
            if (returnProp != null && cppRet == "") return false;

            // Parameters (excludes return parm)
            var paramProps = GetParamProperties(func).ToList();
            var cppParamParts = new List<string>();
            var argNames = new List<string>();

            bool isConst = func.FunctionFlags.HasAnyFlags(EFunctionFlags.Const);
            bool isStatic = func.FunctionFlags.HasAnyFlags(EFunctionFlags.Static);

            if (!isStatic)
                cppParamParts.Add($"{cls.SourceName}*{(isConst ? " const" : "")} Self");

            foreach (var p in paramProps)
            {
                string? cppType = MapPropertyCppType(p, isParam: true, registeredTypeNames);
                if (cppType == null) return false;
                cppParamParts.Add($"{cppType} {p.SourceName}");
                argNames.Add(p.SourceName);
            }

            string paramStr = string.Join(", ", cppParamParts);
            string argStr = string.Join(", ", argNames);
            string retKeyword = returnProp == null ? "" : "return ";
            string call = isStatic
                ? $"{cls.SourceName}::{func.SourceName}({argStr})"
                : $"Self->{func.SourceName}({argStr})";

            wrapperLine = $"static {cppRet} {func.SourceName}({paramStr}) {{ {retKeyword}{call}; }}";
            return true;
        }

        /// <summary>
        /// Tries to build an AngelScript method signature string for RegisterObjectMethod.
        /// Returns false if any parameter/return type cannot be mapped.
        /// </summary>
        private bool TryBuildAsSignature(
            UhtFunction func,
            HashSet<string> registeredTypeNames,
            out string? asSignature)
        {
            asSignature = null;

            var returnProp = GetReturnProperty(func);
            string asRet = returnProp != null
                ? MapPropertyAsType(returnProp, registeredTypeNames) ?? ""
                : "void";
            if (returnProp != null && asRet == "") return false;

            var paramParts = new List<string>();
            foreach (var p in GetParamProperties(func))
            {
                string? asType = MapPropertyAsType(p, registeredTypeNames);
                if (asType == null) return false;
                paramParts.Add($"{asType} {p.SourceName}");
            }

            bool isConst = func.FunctionFlags.HasAnyFlags(EFunctionFlags.Const);
            string constSuffix = isConst ? " const" : "";
            asSignature = $"{asRet} {func.SourceName}({string.Join(", ", paramParts)}){constSuffix}";
            return true;
        }

        // -------------------------------------------------------------------------
        // Helpers – function parameter extraction
        // -------------------------------------------------------------------------

        private static UhtProperty? GetReturnProperty(UhtFunction func)
        {
            return func.Children
                .OfType<UhtProperty>()
                .FirstOrDefault(p => p.PropertyFlags.HasAnyFlags(EPropertyFlags.ReturnParm));
        }

        private static IEnumerable<UhtProperty> GetParamProperties(UhtFunction func)
        {
            return func.Children
                .OfType<UhtProperty>()
                .Where(p => p.PropertyFlags.HasAnyFlags(EPropertyFlags.Parm)
                         && !p.PropertyFlags.HasAnyFlags(EPropertyFlags.ReturnParm));
        }

        // -------------------------------------------------------------------------
        // Type mapping – AngelScript (for method signatures)
        // -------------------------------------------------------------------------

        /// <summary>
        /// Maps a UHT property to an AngelScript type declaration string.
        /// Returns null if the type is not supported (the function will be skipped).
        /// </summary>
        private static string? MapPropertyAsType(UhtProperty property, HashSet<string> registeredTypeNames)
        {
            bool isReturn = property.PropertyFlags.HasAnyFlags(EPropertyFlags.ReturnParm);
            bool isOut = !isReturn && property.PropertyFlags.HasAnyFlags(EPropertyFlags.OutParm);

            switch (property)
            {
                case UhtBoolProperty:
                    return isOut ? "bool &out" : "bool";

                case UhtByteProperty { Enum: null }:
                    return isOut ? "uint8 &out" : "uint8";

                case UhtIntProperty:
                    return isOut ? "int &out" : "int";

                case UhtInt64Property:
                    return isOut ? "int64 &out" : "int64";

                case UhtUInt32Property:
                    return isOut ? "uint &out" : "uint";

                case UhtUInt64Property:
                    return isOut ? "uint64 &out" : "uint64";

                case UhtFloatProperty:
                    return isOut ? "float &out" : "float";

                case UhtDoubleProperty:
                    return isOut ? "double &out" : "double";

                case UhtStrProperty:
                    if (isReturn) return "FString";
                    return isOut ? "FString &out" : "const FString &in";

                case UhtNameProperty:
                    if (isReturn) return "FName";
                    return isOut ? "FName &out" : "const FName &in";

                case UhtTextProperty:
                    if (isReturn) return "FText";
                    return isOut ? "FText &out" : "const FText &in";

                case UhtObjectProperty p when p.Class != null:
                    return $"{p.Class.SourceName}@";

                case UhtClassProperty:
                    return "UClass@";

                case UhtStructProperty p
                        when registeredTypeNames.Contains(p.ScriptStruct.SourceName):
                    if (isReturn) return p.ScriptStruct.SourceName;
                    return isOut
                        ? $"{p.ScriptStruct.SourceName} &out"
                        : $"const {p.ScriptStruct.SourceName} &in";

                case UhtEnumProperty p:
                    return p.Enum.SourceName;

                default:
                    return null;
            }
        }

        // -------------------------------------------------------------------------
        // Type mapping – C++ (for wrapper function signatures)
        // -------------------------------------------------------------------------

        /// <summary>
        /// Maps a UHT property to a C++ type declaration string.
        /// Returns null if the type is not supported.
        /// </summary>
        private static string? MapPropertyCppType(
            UhtProperty property,
            bool isParam,
            HashSet<string> registeredTypeNames)
        {
            bool isReturn = property.PropertyFlags.HasAnyFlags(EPropertyFlags.ReturnParm);
            bool isOut = isParam && !isReturn
                && property.PropertyFlags.HasAnyFlags(EPropertyFlags.OutParm);

            switch (property)
            {
                case UhtBoolProperty:
                    return isOut ? "bool&" : "bool";

                case UhtByteProperty { Enum: null }:
                    return isOut ? "uint8&" : "uint8";

                case UhtIntProperty:
                    return isOut ? "int32&" : "int32";

                case UhtInt64Property:
                    return isOut ? "int64&" : "int64";

                case UhtUInt32Property:
                    return isOut ? "uint32&" : "uint32";

                case UhtUInt64Property:
                    return isOut ? "uint64&" : "uint64";

                case UhtFloatProperty:
                    return isOut ? "float&" : "float";

                case UhtDoubleProperty:
                    return isOut ? "double&" : "double";

                case UhtStrProperty:
                    if (!isParam) return "FString";
                    return isOut ? "FString&" : "const FString&";

                case UhtNameProperty:
                    if (!isParam) return "FName";
                    return isOut ? "FName&" : "const FName&";

                case UhtTextProperty:
                    if (!isParam) return "FText";
                    return isOut ? "FText&" : "const FText&";

                case UhtObjectProperty p when p.Class != null:
                    return $"{p.Class.SourceName}*";

                case UhtClassProperty:
                    return "UClass*";

                case UhtStructProperty p
                        when registeredTypeNames.Contains(p.ScriptStruct.SourceName):
                    if (!isParam) return p.ScriptStruct.SourceName;
                    return isOut
                        ? $"{p.ScriptStruct.SourceName}&"
                        : $"const {p.ScriptStruct.SourceName}&";

                case UhtEnumProperty p:
                    return p.Enum.SourceName;

                default:
                    return null;
            }
        }
    }
}
